version: "3.8"
 
services:
  paymybuddy-db:
    image: seeb961/paymybuddy-db:latest  
    container_name: paymybuddy-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_paymybuddy
      MYSQL_USER: paymybuddy
      MYSQL_PASSWORD: paymybuddy
 
  paymybuddy-backend:
    image: seeb961/paymybuddy-backend:latest  
    container_name: paymybuddy-backend
    ports:
      - "8080:8080"
    depends_on:
      - paymybuddy-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
      SPRING_DATASOURCE_USERNAME: paymybuddy
      SPRING_DATASOURCE_PASSWORD: paymybuddy
 
volumes:
  db_data:

